### ISSUE TITLE
Polish the Hierplane integration into the AllenNLP demo.

### ISSUE THREAD

**Issue by codeviking** [allenai/hierplane#63]
There are some UX / UI issues associated with the integration of Hierplane into the AllenNLP demo.  We should:

* Fix these.
* Add options / incorporate changes into the library itself where appropriate.

**Comment by codeviking** [comment]
This can't be accomplished until https://github.com/allenai/allennlp/pull/526 lands.

**Comment by DeNeutoy** [comment]
Adding a few minor style things here for the polish: 

Is it possible to make the text inside the boxes wrap, so that the full tree fits in the space?
<img width="705" alt="screen shot 2017-11-22 at 9 43 52 am" src="https://user-images.githubusercontent.com/16001974/33142011-d8b8d6fc-cf69-11e7-8c4c-5d4bc79d199e.png">

The box containing the passage could be bigger, so that you can see all of the text for long sentences without having to scroll.
<img width="711" alt="screen shot 2017-11-22 at 9 42 06 am" src="https://user-images.githubusercontent.com/16001974/33142044-fa5548fe-cf69-11e7-8cc0-763fadfe6f5c.png">

**Comment by aaronsarnat** [comment]
Seems like these problems have been addressed and this issue can be closed. @codeviking would you concur?

**Comment by codeviking** [comment]
Yup, we're good to go in this regard!
